spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/delivery?useSSL=false&serverTimezone=UTC
    username: mysql_user
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
jwt:
  signing:
    key:
      secret: mySecret
  token:
    expiration:
      in-ms: 18000000